# Generated by Django 3.2.6 on 2024-01-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('dispositivo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_asociado', to='home.dispositivo')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.TextField()),
                ('duracion', models.DurationField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conductor')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='vehiculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo_asociado', to='home.vehiculo'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='estacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.estacion'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.vehiculo'),
        ),
    ]
