# Generated by Django 3.2.6 on 2024-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('distancia_recorrida', models.FloatField()),
                ('eventos_reales', models.IntegerField()),
                ('puntuacion_ecologica', models.IntegerField()),
                ('harsh_accelerations', models.IntegerField()),
                ('harsh_brakings', models.IntegerField()),
                ('harsh_cornerings', models.IntegerField()),
                ('geojson_data', models.JSONField()),
            ],
            options={
                'db_table': 'eco_scores',
            },
        ),
    ]
