# Generated by Django 3.2.6 on 2024-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viajes',
            name='device_imei',
        ),
        migrations.AddField(
            model_name='viajes',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
