# Generated by Django 3.2.6 on 2024-01-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ecoscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecoscore',
            options={'managed': False},
        ),
    ]
