# Generated by Django 3.2.6 on 2024-01-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ecoscore_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecoscore',
            options={},
        ),
    ]
