# Generated by Django 3.2.6 on 2024-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ecoscore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoscore',
            name='eventos_permitidos_por_km',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecoscore',
            name='puntuacion_ecologica',
            field=models.FloatField(),
        ),
    ]
