# Generated by Django 3.2.6 on 2024-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240127_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoscore',
            name='device_imei',
            field=models.CharField(default=0.0, max_length=15),
            preserve_default=False,
        ),
    ]
